package crd.student.api.model;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade_1_id
     *
     * @mbg.generated
     */
    private Integer grade1Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade_2_id
     *
     * @mbg.generated
     */
    private Integer grade2Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade_3_id
     *
     * @mbg.generated
     */
    private Integer grade3Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade_4_id
     *
     * @mbg.generated
     */
    private Integer grade4Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade_5_id
     *
     * @mbg.generated
     */
    private Integer grade5Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade_6_id
     *
     * @mbg.generated
     */
    private Integer grade6Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbg.generated
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birth
     *
     * @mbg.generated
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.nation
     *
     * @mbg.generated
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.parent_name
     *
     * @mbg.generated
     */
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.start_school
     *
     * @mbg.generated
     */
    private Date startSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.hukou
     *
     * @mbg.generated
     */
    private String hukou;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade_1_id
     *
     * @return the value of student.grade_1_id
     *
     * @mbg.generated
     */
    public Integer getGrade1Id() {
        return grade1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade_1_id
     *
     * @param grade1Id the value for student.grade_1_id
     *
     * @mbg.generated
     */
    public void setGrade1Id(Integer grade1Id) {
        this.grade1Id = grade1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade_2_id
     *
     * @return the value of student.grade_2_id
     *
     * @mbg.generated
     */
    public Integer getGrade2Id() {
        return grade2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade_2_id
     *
     * @param grade2Id the value for student.grade_2_id
     *
     * @mbg.generated
     */
    public void setGrade2Id(Integer grade2Id) {
        this.grade2Id = grade2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade_3_id
     *
     * @return the value of student.grade_3_id
     *
     * @mbg.generated
     */
    public Integer getGrade3Id() {
        return grade3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade_3_id
     *
     * @param grade3Id the value for student.grade_3_id
     *
     * @mbg.generated
     */
    public void setGrade3Id(Integer grade3Id) {
        this.grade3Id = grade3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade_4_id
     *
     * @return the value of student.grade_4_id
     *
     * @mbg.generated
     */
    public Integer getGrade4Id() {
        return grade4Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade_4_id
     *
     * @param grade4Id the value for student.grade_4_id
     *
     * @mbg.generated
     */
    public void setGrade4Id(Integer grade4Id) {
        this.grade4Id = grade4Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade_5_id
     *
     * @return the value of student.grade_5_id
     *
     * @mbg.generated
     */
    public Integer getGrade5Id() {
        return grade5Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade_5_id
     *
     * @param grade5Id the value for student.grade_5_id
     *
     * @mbg.generated
     */
    public void setGrade5Id(Integer grade5Id) {
        this.grade5Id = grade5Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade_6_id
     *
     * @return the value of student.grade_6_id
     *
     * @mbg.generated
     */
    public Integer getGrade6Id() {
        return grade6Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade_6_id
     *
     * @param grade6Id the value for student.grade_6_id
     *
     * @mbg.generated
     */
    public void setGrade6Id(Integer grade6Id) {
        this.grade6Id = grade6Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbg.generated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbg.generated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.birth
     *
     * @return the value of student.birth
     *
     * @mbg.generated
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.birth
     *
     * @param birth the value for student.birth
     *
     * @mbg.generated
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.nation
     *
     * @return the value of student.nation
     *
     * @mbg.generated
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.nation
     *
     * @param nation the value for student.nation
     *
     * @mbg.generated
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.address
     *
     * @return the value of student.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.address
     *
     * @param address the value for student.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.parent_name
     *
     * @return the value of student.parent_name
     *
     * @mbg.generated
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.parent_name
     *
     * @param parentName the value for student.parent_name
     *
     * @mbg.generated
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.start_school
     *
     * @return the value of student.start_school
     *
     * @mbg.generated
     */
    public Date getStartSchool() {
        return startSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.start_school
     *
     * @param startSchool the value for student.start_school
     *
     * @mbg.generated
     */
    public void setStartSchool(Date startSchool) {
        this.startSchool = startSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.hukou
     *
     * @return the value of student.hukou
     *
     * @mbg.generated
     */
    public String getHukou() {
        return hukou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.hukou
     *
     * @param hukou the value for student.hukou
     *
     * @mbg.generated
     */
    public void setHukou(String hukou) {
        this.hukou = hukou == null ? null : hukou.trim();
    }
}